## Arrays - Parte II
Vamos agora aprender a selecionar elementos e partes de arrays e matrizes. \
Para obter um elemento de um array basta indicar o índice desse elemento. Vamos gerar o array 1...9 e selecionar o elemento 5.

In [1]:
import numpy as np
arr1 = np.arange(1,10)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
arr1[4]

5

Vamos agora selecionar múltiplos elementos de um array. \
Suponha que queremos obter o terceiro, quarto e quinto elementos do array, ou seja, 3, 4 e 5.

In [3]:
arr1[2:5]

array([3, 4, 5])

Agora vamos aprender como obter os primeiros n elementos de um array. \
Suponha que queremos obter os 4 primeiros elementos do nosso array.

In [4]:
arr1[:4]

array([1, 2, 3, 4])

Em seguida, vamos obter os 4 últimos elementos do nosso array.

In [5]:
arr1[5:]

array([6, 7, 8, 9])

Vamos agora criar uma matriz contendo 3 linhas e 10 colunas, da seguinte forma: \
0 .. 9 \
10..19 \
20..29

In [6]:
arr2 = np.linspace(0, 29, 30)
mat1 = arr2.reshape(3, 10)
mat1

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.]])

Agora vamos selecionar elementos e sequências dessa matriz. \
Vamos iniciar selecionando a segunda linha da matriz.

In [7]:
mat1[1]

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

Agora vamos selecionar o elemento 25.

In [8]:
mat1[2,5]

25.0

Vamos agora selecionar os elementos da segunda e terceira colunas da matriz. \
Como temos 3 linhas, queremos obter 6 elementos, da seguinte forma: \
1   2 \
11 12 \
21 22

In [9]:
mat1[0:3, 1:3]

array([[ 1.,  2.],
       [11., 12.],
       [21., 22.]])

Um aspecto interessante da linguagem Python é que eu consigo selecionar elementos com base em condições sem usar estruturas condicionais ou laços. \
Vamos gerar um array contendo dezenas, da seguinte forma: \
0 10 20 ... 100

In [10]:
dezenas = np.arange(0, 101, 10)
dezenas

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

Suponha agora que queremos obter todos os elementos maiores ou iguais a 60. 

In [11]:
dezenas >= 60

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [12]:
dezenas[dezenas >= 60]

array([ 60,  70,  80,  90, 100])

Note que o vetor não precisa estar ordenado.

In [13]:
dezenas2 = np.array([30, 40, 10, 60, 90, 20, 0, 80, 70, 50, 100])
dezenas2[dezenas2 >= 60]

array([ 60,  90,  80,  70, 100])

Exercício 1 \
Neste exercício você deve criar uma matriz 4 x 10 da seguinte forma: \
01 .. 10 \
11 .. 20 \
21 .. 30 \
31 .. 40 \
Em seguida, você deve pegar os elementos centrais da matriz, ou seja: \
14 15 16 17 \
24 25 26 27

In [14]:
mat2 = np.arange(1, 41).reshape(4, 10)
mat2[1:3, 3:7]

array([[14, 15, 16, 17],
       [24, 25, 26, 27]])