## Operações com Arrays 
Podemos operar com diversos (ou todos) elementos de um array numa única operação. \
Suponha que tenhamos o array 0..9 e queremos somar 10 a todos os elementos do array. É possível fazer essa operação sem usar um laço? Em Python, sim!

In [1]:
import numpy as np
arr1 = np.arange(0, 10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
arr1 + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Se fizermos arr1 - 10 teremos o vetor original?

In [3]:
arr1 - 10

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

Vamos agora criar outro array (arr2), contendo os elementos 10..19. \
Assim como somamos um inteiro aos elementos de um array, podemos somar dois arrays. \
Vejamos o resultado de arr1 + arr2:

In [4]:
arr2 = np.arange(10, 20)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [5]:
arr1 + arr2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

Para alterar um elemento do array, basta indicar o índice desse elemento. \
Ex: alterar o primeiro elemento de arr1, colocando 10 no lugar de 0.

In [6]:
arr1[0] = 10
arr1

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

E se quisermos alterar todos os elementos do array, colocando 10 em todas as posições?

In [7]:
arr1[:] = 10
arr1

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

Exercício 1 \
Altere os 5 primeiros elementos de arr1, colocando o valor 20.

In [8]:
arr1[:5] = 20
arr1

array([20, 20, 20, 20, 20, 10, 10, 10, 10, 10])

Exercício 2 \
Altere os 3 últimos elementos de arr1, colocando o valor 30.

In [9]:
arr1[7:] = 30
arr1


array([20, 20, 20, 20, 20, 10, 10, 30, 30, 30])

Vamos agora criar um novo array (arr3), utilizando os 5 primeiros elementos de arr2. 

In [10]:
arr3 = arr2[:5]
arr3

array([10, 11, 12, 13, 14])

A seguir, vamos colocar 0 em todos os elementos de arr3 e observar o que acontece com arr2.

In [11]:
arr3[:] = 0
arr2

array([ 0,  0,  0,  0,  0, 15, 16, 17, 18, 19])

O que aconteceu foi que arr3 não foi criado com novos valores. Este array "aponta" para os 5 primeiros valores de arr2. Assim, ao alterar os elementos de arr3, alteramos também os 5 primeiros elementos de arr2.

A função reshape do numpy permite mesclar dois arrays.

In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
result = arr.reshape(-1)
result

[[1 2 3]
 [4 5 6]]


array([1, 2, 3, 4, 5, 6])

Apendando arrays

In [13]:
arr4 = np.arange(0, 10)
arr5 = np.arange(10, 20)
print(arr4)
print(arr5)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [14]:
arr5 = np.append(arr4, arr5)
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

Exercício 3 \
Escreva um programa que gere o seguinte array: [1, 2, 3, 4, 5]. Em seguida, leia 5 valores digitados pelo usuário e os apende no array inicial. Finalmente, print o array resultante.

In [15]:
arr6 = np.arange(1, 6)
l = []
for f in range(5):
    nro = input('Digite um número: ')
    l.append(nro)
arr7 = np.array(l)
arr8 = np.append(arr6, arr7)
arr8

array(['1', '2', '3', '4', '5', '', '1', '2', '3', '4'], dtype='<U11')

Exercício 4 \
Crie um array de 20 elementos contendo valores entre 1 e 100. Em seguida, leia valores digitados pelo usuário até que o valor lido conste no array. Ao final, print o array e o último valor lido.

In [ ]:
rng = np.random.default_rng() # inicializa o gerador de números aleatórios
arr9 = rng.integers(low=1, high=101, size=20) # gera o vetor de números aleatórios 
while True:
    nro =int(input('Digite um número: '))
    if nro in arr9:
        break
print(arr9)
print(nro)

[54 78 36 19 33  1 58 64 85 92 76 62 88 36 49 28 70 13 68 55]
[54 78 36 19 33  1 58 64 85 92 76 62 88 36 49 28 70 13 68 55]
55
